config/routes.rb
Rails.application.routes.draw do
  resources :users
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.turbo_stream { redirect_to users_url }
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.turbo_stream { redirect_to users_url }
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.turbo_stream {
          @user.broadcast_replace_to('user_card', target: helpers.dom_id(@user, :card))
          redirect_to user_url(@user)
        }
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.turbo_stream { redirect_to user_url(@user) }
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :email, :admin, :active, :validated, :user_data, :deactivated_at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Home</h1>
<p>homepage</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UserRoster</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
		<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
			<div class="container-fluid">
				<a class="navbar-brand" href="/">User Roster</a>
				<button class="navbar-toggler" type="button"
								data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
								aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarNavDropdown">
					<ul class="navbar-nav">
						<li class="nav-item">
							<a class="nav-link" href="<%= users_path %>">Users</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>

		<main class="container">
			<%= yield %>
		</main>
  </body>
</html>

app/views/users/_form.html.erb
<% form_url = user.new_record? ? users_url : user_url(user) %>
<div class="card">
	<div class="card-body">
		<%= form_with model: user, url: form_url, format: :turbo_stream do |form| %>
			<h5 class="card-title">
				<%= form.label :username %>
				<%= form.text_field :username%>
			</h5>
			<p class="user-email">
				<%= form.label :email %>
				<%= form.text_field :email %>
			</p>

			<p class="user-details">
				<%= form.check_box :admin, class: "btn-check", checked: user.admin, autocomplete: "off" %>
				<%= form.label :admin, class: "btn btn-outline-primary" %>

				<%= form.check_box :active, class: "btn-check", checked: user.active, autocomplete: "off" %>
				<%= form.label :active, class: "btn btn-outline-primary" %>

				<%= form.check_box :validated, class: "btn-check", checked: user.validated, autocomplete: "off" %>
				<%= form.label :validated, class: "btn btn-outline-primary" %>
			</p>

			<% if user.errors.any? %>
				<div style="color: red">
					<h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

					<ul>
						<% user.errors.each do |error| %>
							<li><%= error.full_message %></li>
						<% end %>
					</ul>
				</div>
			<% end %>

			<div class="user-links">
				<%= form.submit %>
				<a class="card-link" href="<%= user_path(user) %>">Back</a>
			</div>
		<% end %>
	</div>
</div>

app/views/users/_user.html.erb
<%= turbo_frame_tag dom_id(user, :card) do %>
	<div class="card">
		<div class="card-body">
			<h5 class="card-title"><%= user.username %></h5>
			<p class="user-email">
				<%= user.email %>
			</p>
			<p class="user-details">
				<% if user.deactivated_at %>
					<em>Deactivated At <%= user.deactivated_at.iso8601 %></em>
				<% else %>
					<% if user.admin %>
						<span class="badge bg-primary">Admin</span>
					<% end %>
					<% unless user.active %>
						<span class="badge bg-secondary">Inactive</span>
					<% end %>
					<% unless user.validated %>
						<span class="badge bg-warning">Not Validated</span>
					<% end %>
				<% end %>
			</p>
			<div class="user-links">
				<a href="<%= user_path(user) %>" target="_top" class="card-link">View User</a>
				<a href="<%= edit_user_path(user) %>" class="card-link">Edit</a>
			</div>
		</div>
	</div>
<% end %>

app/views/users/_user_backup.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Username:</strong>
    <%= user.username %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>Admin:</strong>
    <%= user.admin %>
  </p>

  <p>
    <strong>Active:</strong>
    <%= user.active %>
  </p>

  <p>
    <strong>Validated:</strong>
    <%= user.validated %>
  </p>

  <p>
    <strong>User data:</strong>
    <%= user.user_data %>
  </p>

  <p>
    <strong>Deactivated at:</strong>
    <%= user.deactivated_at %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= turbo_frame_tag dom_id(@user, :card) do %>
	<%= render "form", user: @user %>
<% end %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<%= link_to "New user", new_user_path %>

<%= turbo_stream_from 'user_card' %>

<div id="users" class="container">
  <% @users.each do |user| %>
    <%= render user %>
  <% end %>
</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>